### ISSUE TITLE
Publish source?

### ISSUE THREAD

**Issue by Cynosphere** [js6pak/mojangfix#1]
I will be willing to move this over to using Cursed Legacy Fabric's "toolchain" apposed to your own builds of loader and such if you're willing to actually publish the source.

**Comment by js6pak** [comment]
Tbh I don't like cursed fabric at all, recently I was trying to build this again using latest fabric but it didn't work, I could try again tho

**Comment by mintoyatsu** [comment]
gib source

**Comment by js6pak** [comment]
(Rewritten) source has been giben (only took 2 years). Still not using cursed, this time it's [babric](https://github.com/babric/). It's based on cursed intermediaries (so should work with cursed mods) but it's not cursed.
